### ISSUE TITLE
Hangs on 'npm i'

### ISSUE THREAD

**Issue by DHirani** [dsuryd/dotnetify-react-demo-vs2017#9]
When running npm i, it just hangs with the following warning

E:\Temp\test\MyApp>npm i
npm WARN deprecated babel-preset-es2015@6.24.1: �  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN engine react-hot-loader@3.1.1: wanted: {"node":">= 6"} (current: {"node":"4.4.3","npm":"2.15.1"})
npm WARN optional dep failed, continuing fsevents@1.1.3

Then if I abort it and press npm i it finishes without any errors but does nothing.
Then when I run dotnet build I get following error message.

E:\Temp\test\MyApp>dotnet build
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 32.66 ms for E:\Temp\test\MyApp\myapp.csproj.
  Restore completed in 80.65 ms for E:\Temp\test\MyApp\myapp.csproj.
  myapp -> E:\Temp\test\MyApp\bin\Debug\netcoreapp2.0\myapp.dll
  v4.4.3
  Performing first-run Webpack build...
  module.js:327
      throw err;
      ^

EXEC : error : Cannot find module 'yargs' [E:\Temp\test\MyApp\myapp.csproj]
      at Function.Module._resolveFilename (module.js:325:15)
      at Function.Module._load (module.js:276:25)
      at Module.require (module.js:353:17)
      at require (internal/module.js:12:17)
      at Object.<anonymous> (E:\Temp\test\MyApp\node_modules\webpack\bin\webpack.js:16:13)
      at Module._compile (module.js:409:26)
      at Object.Module._extensions..js (module.js:416:10)
      at Module.load (module.js:343:32)
      at Function.Module._load (module.js:300:12)
      at Function.Module.runMain (module.js:441:10)
E:\Temp\test\MyApp\myapp.csproj(29,5): error MSB3073: The command "node node_modules/webpack/bin/webpack.js" exited with code 1.

Build FAILED.

**Comment by DHirani** [comment]
just had to leave it running longer it took 15 minutes to run
